export const practices = [
  {
    slug: 'personal-injury',
    name: 'Personal Injury',
    line: 'When carelessness changes a life, we take the insurance company seriously.',
    image: 'tulsa-street.jpg',
    href: '/practice/personal-injury',
    hasPage: true,
    summary:
      'When you have been injured because of someone else’s carelessness, you need counsel who has actually done this work in Oklahoma. Our team has represented thousands of injured Oklahomans and recovered millions of dollars for our clients. We handle the claim so you can focus on recovery.',
    matters: [
      'Oklahoma car accidents',
      'Motorcycle and bike accidents',
      'Tractor-trailer and semi accidents',
      'Premises liability (slip and fall)',
      'Dog bites and animal attacks',
      'Medical malpractice and nursing-home negligence',
      'Wrongful death claims',
    ],
  },
  {
    slug: 'family-law',
    name: 'Family Law',
    line: 'Divorce, custody, and the orders that shape a household.',
    image: 'tulsa-aerial.jpg',
    href: '/practice/family-law',
    hasPage: true,
    summary:
      'Family lawyers have a broader scope than most practice areas. Our Tulsa attorneys handle agreed and high-conflict divorces, child custody and visitation, support, paternity, modifications, guardianships, and step-parent adoptions. We work for a clear, enforceable result — not a longer fight than the family can bear.',
    matters: [
      'Divorce (agreed to contested)',
      'Child custody and visitation',
      'Child support calculation and collection',
      'Paternity determinations',
      'Modifications of court orders',
      'Guardianships',
      'Step-parent adoptions',
    ],
  },
  {
    slug: 'criminal-defense',
    name: 'Criminal Defense',
    line: 'Today’s charge follows you for the rest of your record.',
    image: 'tulsa-dusk.jpg',
    href: '/practice/criminal-defense',
    hasPage: true,
    summary:
      'Criminal charges are difficult. You need a Tulsa criminal defense attorney who takes the case personally — because the outcome is not only jail time, it is a record that follows you. We represent Oklahomans on matters ranging from traffic and misdemeanors to felony, DUI, drug, and serious violent charges.',
    matters: [
      'Felony and misdemeanor',
      'DUI / DWI / TOC',
      'Drug charges',
      'Assault and battery',
      'Expungement',
      'Serious felony charges',
    ],
  },
  {
    slug: 'workers-compensation',
    name: 'Workers’ Compensation',
    line: 'Medical care, temporary disability, and the settlement you are owed.',
    image: 'tulsa-street.jpg',
    href: '/practice',
    hasPage: false,
    summary:
      'Workers’ compensation insurance is supposed to provide medical treatment and, when you cannot work, temporary disability. Many claims are delayed or denied. Our Tulsa work-injury attorneys represent clients through treatment, surgery cases, and settlement — including back, shoulder, knee, hand, and wrist injuries.',
    matters: ['Falls at work', 'Carpal tunnel', 'Surgery cases', 'Back and neck injuries', 'Denied claims', 'Disfigurement'],
  },
  {
    slug: 'business-law',
    name: 'Business Law',
    line: 'Formation through dispute — for the life of the company.',
    image: 'tulsa-aerial.jpg',
    href: '/practice',
    hasPage: false,
    summary:
      'We represent sole proprietors, LLCs, partnerships, and corporations across Oklahoma. From entity formation and contracts to intellectual property and commercial disputes, the goal is the same: protect the business without spending it on litigation that does not pay.',
    matters: [
      'Business organization',
      'Corporations and LLCs',
      'Partnerships',
      'Patents, trademarks, copyright',
      'Contracts and disputes',
    ],
  },
  {
    slug: 'bankruptcy',
    name: 'Bankruptcy',
    line: 'A fresh start when creditor calls will not stop.',
    image: 'tulsa-dusk.jpg',
    href: '/practice',
    hasPage: false,
    summary:
      'Chapter 7 and Chapter 13 filings in Tulsa do not have to be opaque. Bankruptcy can stop garnishments, halt collection, and protect most assets so you can rebuild credit. If you cannot make the bills each month, a free telephone consultation is the right first step.',
    matters: ['Oklahoma Chapter 7', 'Oklahoma Chapter 13'],
  },
  {
    slug: 'estate-planning',
    name: 'Estate Planning & Probate',
    line: 'Wills, trusts, and a plan that actually holds in Oklahoma.',
    image: 'tulsa-aerial.jpg',
    href: '/practice',
    hasPage: false,
    summary:
      'Our Tulsa estate planning and probate attorneys help you avoid unnecessary probate stress and put assets where you intend — Last Will, revocable living trust, durable power of attorney — under Oklahoma law.',
    matters: ['Wills', 'Trusts', 'Probate', 'Powers of attorney'],
  },
  {
    slug: 'immigration',
    name: 'Immigration',
    line: 'Visas, green cards, and removal — in English and Spanish.',
    image: 'tulsa-street.jpg',
    href: '/practice',
    hasPage: false,
    summary:
      'The Oklahoma immigration attorneys at Kania Law Office handle employment, family, and student visas, asylum, deportation and removal, and green-card matters. The office serves clients in English and Spanish.',
    matters: [
      'Employment-based visas',
      'Family-based visas',
      'Student visas',
      'Asylum and refugee',
      'Deportation and removal',
      'Green cards',
    ],
  },
  {
    slug: 'tax',
    name: 'Tax Services',
    line: 'Preparation, resolution, and IRS representation.',
    image: 'tulsa-dusk.jpg',
    href: '/practice',
    hasPage: false,
    summary:
      'Tax preparation for individuals and businesses, bookkeeping, audit support, and IRS representation when you need counsel in the room — not only a return filed.',
    matters: ['Individual and business filing', 'Tax resolution', 'Bookkeeping', 'IRS representation'],
  },
]
